---
- name: gather facts based on ec2 metadata
  ec2_facts:
- name: ensure required packages installed
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - git
    - python-pip
- name: synchronize source tree
  synchronize: src=. dest=/opt/ansible-aws recursive=yes delete=yes archive=no
- name: ensure pip packages installed
  pip:
    requirements: /opt/ansible-aws/requirements.txt
# This task needs to use template because ini_file can't handle uwsgi's duplicate keys
- name: ensure uwsgi config file in place
  template: src=uwsgi_dev.ini dest=/etc/uwsgi/
- name: ensure nginx config file in place
  template: src=nginx_dev.conf dest=/etc/nginx/sites-available
- name: ensure nginx site enabled
  file: src=/etc/nginx/sites-available/nginx_dev.conf dest=/etc/nginx/sites-enabled/nginx_dev.conf state=link
- name: ensure services reloaded
  service: name={{ item }} state=reloaded
  with_items:
    - nginx
    - uwsgi
