---
- name: gather facts based on ec2 metadata
  ec2_facts:
- name: ensure required packages installed
  apt: name={{ item }} state=present
  with_items:
    - git
    - python-pip
- name: synchronize source tree
  synchronize: src=../app dest=/opt recursive=yes delete=yes archive=no
- name: ensure pip packages installed
  pip:
    requirements: /opt/app/requirements.txt
# This task needs to use template because ini_file can't handle uwsgi's duplicate keys
- name: ensure uwsgi config file in place
  copy: src=hello.ini dest=/etc/uwsgi/
- name: ensure nginx config file in place
  copy: src=hello.conf dest=/etc/nginx/sites-available/
- name: ensure nginx site enabled
  file: src=/etc/nginx/sites-available/hello.conf dest=/etc/nginx/sites-enabled/hello.conf state=link
- name: ensure services reloaded
  service: name={{ item }} state=reloaded
  with_items:
    - nginx
    - uwsgi
